### ISSUE TITLE
Crashes after most recent update

### ISSUE THREAD

**Issue by Sverreg** [bene51/3Dscript#17]
After using 3Dscript successfully about a month ago, it now crashes, either as soon as I enable light, or just upon changing the channel. The plugin freezez and has to be restarted.

`Exception in thread "3D-Animation rendering thread" java.lang.RuntimeException: OpenCL error 4294967245: CL_INVALID_ARG_SIZE in H:\fijiplugins\3D_Animation\3D_Animation_Native\Raycaster.cpp (line 436)
	at animation3d.renderer3d.OpenCLRaycaster.cast(Native Method)
	at animation3d.renderer3d.OpenCLRaycaster.project(OpenCLRaycaster.java:240)
	at animation3d.renderer3d.Renderer3D.render(Renderer3D.java:133)
	at animation3d.gui.RenderingThread.render(RenderingThread.java:115)
	at animation3d.gui.RenderingThread.loop(RenderingThread.java:65)
	at animation3d.gui.RenderingThread$1.run(RenderingThread.java:49)
`

![image](https://user-images.githubusercontent.com/27206049/56847910-5d604a80-68e2-11e9-9cbe-75782fbcd4ba.png)

I installed 3Dscript on a fresh Fiji from the romulus.oice... update site.

**System information:**
Win 10 Enterprise (64bit).
Intel Xeon CPU E5-1630 v4 3.70GHz
128GB RAM
Radeon RX 580, 8GB dedicated memory
![image](https://user-images.githubusercontent.com/27206049/56847951-da8bbf80-68e2-11e9-8d0e-cfcacb6e1800.png)

And while I'm here; thanks for creating and sharing this plugin, it's amazing.

**Comment by Sverreg** [comment]
Of course I figured out my mistake just after submitting an issue. Closing the composite imagej outside of 3dscript causes all kinds of crashes. Maybe this is obvious but I guess it could be mentioned somewhere, the error messages are not clear.
