### ISSUE TITLE
OpenCL error: CL_INVALID_ARG_SIZE

### ISSUE THREAD

**Issue by bruvellu** [bene51/3Dscript#33]
Hi Bene,

3Dscript stopped working in one of our Linux workstations. We didn't make any changes to the system except for Fiji updates. CLIJ still works fine with the GPU, so it seems specific to 3Dscript. Maybe it's related to the latest March updates?

The plugin fails with the following error:

```
(Fiji Is Just) ImageJ 2.9.0/1.53t; Java 1.8.0_322 [64-bit]; Linux 3.10.0-1062.4.3.el7.x86_64; 643MB of 93994MB (<1%)
 
java.lang.RuntimeException: OpenCL error 4294967245: CL_INVALID_ARG_SIZE in /3Dscript/3D_Animation_Native/Raycaster.cpp (line 624)
	at animation3d.renderer3d.OpenCLRaycaster.cast(Native Method)
	at animation3d.renderer3d.OpenCLRaycaster.project(OpenCLRaycaster.java:317)
	at animation3d.renderer3d.Renderer3D.render(Renderer3D.java:151)
	at animation3d.gui.RenderingThread.<init>(RenderingThread.java:38)
	at animation3d.main.InteractiveRaycaster.run(InteractiveRaycaster.java:174)
	at ij.plugin.filter.PlugInFilterRunner.processOneImage(PlugInFilterRunner.java:266)
	at ij.plugin.filter.PlugInFilterRunner.<init>(PlugInFilterRunner.java:114)
	at ij.IJ.runUserPlugIn(IJ.java:239)
	at ij.IJ.runPlugIn(IJ.java:203)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:70)
	at java.lang.Thread.run(Thread.java:750)
```

And this is the GPU information identified by CLIJ:

```
Available CL backends:
  * net.haesleinhuepf.clij.clearcl.backend.jocl.ClearCLBackendJOCL@381eec20
    Functional backend:net.haesleinhuepf.clij.clearcl.backend.jocl.ClearCLBackendJOCL@26b54469
    Best backend:net.haesleinhuepf.clij.clearcl.backend.jocl.ClearCLBackendJOCL@32e159e0
Used CL backend: net.haesleinhuepf.clij.clearcl.backend.jocl.ClearCLBackendJOCL@662ed2bf
ClearCL: ClearCLBase [mClearCLBackendInterface=net.haesleinhuepf.clij.clearcl.backend.jocl.ClearCLBackendJOCL@662ed2bf, mPeerPointer=null]
  Number of platforms:1
  [0] NVIDIA CUDA
     Number of devices: 1
     Available devices: 
     [0] GeForce GTX TITAN X 
        NumberOfComputeUnits: 24 
        Clock frequency: 1076 
        Version: 1.2 
        Extensions: cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts cl_khr_gl_event cl_nv_create_buffer cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_device_uuid 
        GlobalMemorySizeInBytes: 12805668864 
        LocalMemorySizeInBytes: 49152 
        MaxMemoryAllocationSizeInBytes: 3201417216 
        MaxWorkGroupSize: 1024 
        Compatible image types: [SignedNormalizedInt8, SignedNormalizedInt16, UnsignedNormalizedInt8, UnsignedNormalizedInt16, SignedInt8, SignedInt16, SignedInt32, UnsignedInt8, UnsignedInt16, UnsignedInt32, HalfFloat, Float]
Best GPU device for images: GeForce GTX TITAN X
Best largest GPU device: GeForce GTX TITAN X
Best CPU device: GeForce GTX TITAN X
```

Any hints of what could be the issue?

Thanks!
Bruno

**Comment by bene51** [comment]
Hi Bruno,

seems that the wrong file made it into the updater. I just updated and uploaded the library file for Linux again, can you please run the updater and check whether it's working afterwards?

Best wishes,
Bene

**Comment by bruvellu** [comment]
Hi Bene, it's working after the update. Thanks for the prompt fix! And by the way, thanks for 3Dscript itself. It was critical for visualizing the light sheet data in our [recent paper](https://www.biorxiv.org/content/10.1101/2023.03.30.534554v1). Cheers
